### ISSUE TITLE
Can't compile in Ubuntu 22.04

### ISSUE THREAD

**Issue by FeedehC** [FirelandsProject/firelands-cata#148]
### Current Behaviour

Cannot compile the core using Ubuntu 22.04

### Expected Blizzlike Behaviour

Compile

### Source

![image](https://github.com/FirelandsProject/firelands-cata/assets/56729512/a6aa4e94-83f6-4c68-a39e-f4d1caa12d01)

### Steps to reproduce the problem

1) Install Ubuntu 22.04
2) Install reqs
3) Cmake and make

### Extra Notes

I think it is related to the OpenSSL version, Ubuntu 20.04 used to have v1.x and 22.04 have v3.x and that might be causing the issue. I remember having a similar issue in AzerothCore when changed from 20.04 to 22.04

### FC rev. hash/commit

29381b27d95a75fb9e2c10ac330a3b7a450680ee

### Operating system

Ubuntu 22.04

**Comment by seobryn** [comment]
Hi @FeedehC  can you please share with us What version of OpenSSL are you usign? I think you have the wrong version, you need the Open SSL 1.1 to compile firelands

**Comment by Meltie2013** [comment]
@FeedehC Ubuntu 22.04, 22.10 and 23.04 ship with OpenSSL 3.x by default. You can follow the small guide below to have a successful compile.

Remove OpenSSL related packages.
```
sudo apt remove openssl libssl-dev
```

Install OpenSSL 1.1.1 related packages
```
# Download OpenSSL 1.1.1f packages
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2.19_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.19_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb

# Install required packages
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i openssl_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2.19_amd64.deb
```

Also, you can hold the packages back as well to prevent them upgrading to OpenSSL 3.x again.
```
sudo apt-mark hold openssl
sudo apt-mark hold libssl-dev
```

If you have any issues, feel free to comment it here.

**Comment by seobryn** [comment]
So, if there's anything, I'm going to close the Issue

**Comment by FeedehC** [comment]
Thank you!
