### ISSUE TITLE
To Greymane Manor - Quest: 14465

### ISSUE THREAD

**Issue by pangolp** [FirelandsProject/firelands-cata#28]
### Current Behaviour

Neither the npc nor the horses appear from the beginning to the end of the mission it should be noted that you have to put gm on to visualize the npc and complete the mission

### Expected Blizzlike Behaviour

When arriving at the mansion, the npc should be visible, in order to continue with the chain of missions.

### Source

- https://www.wowhead.com/quest=14465/to-greymane-manor
- https://www.wowhead.com/npc=36452/gwen-armstead
- https://www.wowhead.com/npc=36606/queen-mia-greymane
- https://www.wowhead.com/spell=82892/update-bind-to-greymane-manor
- https://www.wowhead.com/spell=69254/carriage-ride
- https://www.wowhead.com/spell=69255/summon-swift-mountain-horse
- https://www.wowhead.com/spell=69256/forcecast-summon-swift-mountain-horse
- https://www.wowhead.com/npc=36741/swift-mountain-horse

### Steps to reproduce the problem

1. Take the quest
2. Go to the castle to complete it
(Although the castle should be reached by horse).
- https://medal.tv/es/games/requested/clips/y4rmA-_UJTeGb/d1337Ade0NmB

### Extra Notes

None

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/dce019da37cbddd4752723d17d909832fa34ee05

### Operating system

Windows

### Custom changes or Modules

None

**Comment by pangolp** [comment]
```
.go xyz -1691.4219 2495.9705 95.82897
.go xyz -1789.1941 2354.1392 37.30597
.go xyz -1782.6941 2382.6392 43.55597
.go xyz -1778.9441 2422.8892 55.80597
.go xyz -1758.4441 2461.6392 68.05597
.go xyz -1711.1941 2466.3892 83.05597
```

**Comment by kuramajssken001** [comment]
@pangolp Try again

**Comment by pangolp** [comment]
> @pangolp Try again

I will check it out. Thank you.
