### ISSUE TITLE
The Hungry Ettin - Quest: 14416

### ISSUE THREAD

**Issue by pangolp** [FirelandsProject/firelands-cata#35]
### Current Behaviour

When we get on the horse and try to use the rope nothing happens. Similarly, if we go to the npc, we do not get credit for the horses.

### Expected Blizzlike Behaviour

We should be able to get more horses, using the rope, and when we get to the npc, we should get the credit, until we get the 5 that the mission asks us.

### Source

- https://www.wowhead.com/quest=14416/the-hungry-ettin
- https://www.wowhead.com/npc=36457/lorna-crowley
- https://www.wowhead.com/npc=36540/mountain-horse
- https://www.wowhead.com/npc=36555/mountain-horse
- https://www.wowhead.com/npc=36560/mountain-horse-credit
- https://www.wowhead.com/spell=68917/mountain-horse-credit
- https://www.wowhead.com/spell=68916/mountain-horse-dummy
- https://www.wowhead.com/spell=68903/round-up-horse
- https://www.wowhead.com/spell=68908/rope-in-horse
- https://www.wowhead.com/spell=94654/ride-vehicle

### Steps to reproduce the problem

1. Take the quest, and try to complete it.
2. `quest add 14416`
3. `list c 36457`
4. `go c 255930`

### Extra Notes

None

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/c2d058b15f1ee859bc2db361c2145d172e6c6e25

### Operating system

Windows

### Custom changes or Modules

None

**Comment by kuramajssken001** [comment]
@pangolp Try again.
