### ISSUE TITLE
Dummys moving

### ISSUE THREAD

**Issue by pangolp** [FirelandsProject/firelands-cata#53]
### Current Behaviour

When you hit the Dummies in the initial zones they move.
The error occurs in the initial zone of:

- Night Elf
- Undead.
- Trolls.

In the Golbin there is something curious, only one dummy moves and even if you attack it doesn't attack you, I really don't know if it's a bug, or some strange thing of golbin technology.

### Expected Blizzlike Behaviour

They simply should not move.

### Source

- https://github.com/FirelandsProject/bugtracker/issues/2

### Steps to reproduce the problem

1. Simply attack the dummies in the starting zone of the mentioned races.

### Extra Notes

None

### FC rev. hash/commit

https://github.com/FirelandsProject/firelands-cata/commit/4b6c8f5beea1a1ea6dbbe404bb658aac72029cd7

### Operating system

Windows

### Custom changes or Modules

None

### Screenshots

![WoWScrnShot_090422_150118](https://user-images.githubusercontent.com/112731215/188333296-4e02b480-a7f9-466c-9372-95eb6b368b74.jpg)

![WoWScrnShot_090422_150955](https://user-images.githubusercontent.com/112731215/188333308-f22856a3-d096-4915-b92e-4dd8b1949888.jpg)

![WoWScrnShot_090422_151528](https://user-images.githubusercontent.com/112731215/188333314-fe453b93-2428-4450-9d88-e678eac58ef4.jpg)

![WoWScrnShot_090422_151516](https://user-images.githubusercontent.com/112731215/188333317-44db9b1c-43e7-4755-a637-f699632ea22c.jpg)

**Comment by Meltie2013** [comment]
@pangolp The issue could be the dummies missing some flags. Looking at training dummies and see what flags they have.

**Comment by pangolp** [comment]
> The issue could be the dummies missing some flags. Looking at training dummies and see what flags they have.

Correct, most likely, they are missing the root. I was about to try that.
Thanks for the suggestion. That's why I had assigned it to me.

**Comment by Meltie2013** [comment]
Just checking some other data I have for Cataclysm. I believe unit flag 256 is missing, need to confirm it on sniff data.

**Comment by pangolp** [comment]
> Just checking some other data I have for Cataclysm. I believe unit flag 256 is missing, need to confirm it on sniff data.

To regain your health, you say?

**Comment by Meltie2013** [comment]
> > Just checking some other data I have for Cataclysm. I believe unit flag 256 is missing, need to confirm it on sniff data.
> 
> To regain your health, you say?

![image](https://user-images.githubusercontent.com/5354732/188338225-67b22f34-8b13-4071-a0c8-7b515994ad3b.png)

I am not 100% on this, why I am checking sniff data on the correct flag.

**Comment by pangolp** [comment]
> I am not 100% on this, why I am checking sniff data on the correct flag.

I think not, because if it had that flag, it could not be attacked by the player, and the problem is that it moves, and also, now that I remember, it does not recover life. So I think, what it really lacks, is something else.

It could be this one perhaps: `mechanic_immune_mask`.
64 - 0x0000 0040 - `MECHANIC_ROOT`

**Comment by pangolp** [comment]
But I also think it lacks:

`unit_flags2`: 2048
2048 0x0000 0800 `UNIT_FLAG2_REGENERATE_POWER`
