### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Meltie2013** [FirelandsProject/firelands-cata#91]
**Description:**
- Server crash during startup

**Branch:**
- master

**Commit / Hash:**
- Firelands rev. c7556c2287a7 2022-09-16 21:40:33 +0000 (master branch)

**Operating System:**
- Debian 10

**Cause:**
https://github.com/FirelandsProject/firelands-cata/commit/9537c1b8c35ed6cfb0ec49f3c3f2d337461908d3

[backtrace_2022-09-17-14:10:05.log](https://github.com/FirelandsProject/firelands-cata/files/9592454/backtrace_2022-09-17-14.10.05.log)

**Fix:**
- https://github.com/FirelandsProject/firelands-cata/pull/92

**Comment by seobryn** [comment]
Fixed on #92
