### ISSUE TITLE
Warnings in Ubuntu 20.04

### ISSUE THREAD

**Issue by Tony931023** [FirelandsProject/firelands-cata#98]
### Current Behaviour

[ 15%] Building CXX object src/server/game/CMakeFiles/game.dir/Conditions/ConditionMgr.cpp.o
/home/cloud/firelands-cata/src/server/game/Conditions/ConditionMgr.cpp:620:69: warning: comparison of integers of different signs: 'int32' (aka 'int') and 'const uint32' (aka 'const unsigned int') [-Wsign-compare]
                condMeets = unit->GetPower(Powers(ConditionValue1)) >= ConditionValue2;
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
/home/cloud/firelands-cata/src/server/game/Conditions/ConditionMgr.cpp:622:73: warning: comparison of integers of different signs: 'int32' (aka 'int') and 'const uint32' (aka 'const unsigned int') [-Wsign-compare]
                    condMeets = unit->GetPower(Powers(ConditionValue1)) <= ConditionValue3;
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
2 warnings generated.


### Expected Blizzlike Behaviour

*

### Source

_No response_

### Steps to reproduce the problem

make 
make install

### Extra Notes

_No response_

### FC rev. hash/commit

21bdf1b5cfb4ed1eec3c041f3fd88f021b7e4626

### Operating system

Ubuntu 20.04 

### Custom changes or Modules

_No response_

**Comment by seobryn** [comment]
Hi @Tony931023  can you be more explicit? I can't see any errors on this lines... Only Warnings, and  of course, we are working to fix the warnings

**Comment by Tony931023** [comment]
if they are only warnings when compiling, it was just to tell you that it is giving this when compiling

**Comment by Meltie2013** [comment]
> if they are only warnings when compiling, it was just to tell you that it is giving this when compiling

Upgrade to Ubuntu 21.10. That is a library issue not a source issue. I don't see this warning when compiling the source and I use Arch Linux.

**Comment by pangolp** [comment]
Currently, I think we have almost all the libraries updated, except for C++20, which I think we are using C++17, but even so, within all, it is up to date. So just in case, consider as my colleagues recommended, to update your operating system version. Or, look for the libraries and compile them manually, although that can bring you problems in other projects. It will depend a lot, if the server where you are compiling the project, has this kernel or several. My recommendation is not to use the same server for all projects, because each of them require libraries that may not be compatible with each other.

**Comment by pangolp** [comment]
The idea is always to prevent warnings from appearing, but as we are working on three different operating systems (Windows, Linux and MAC) sometimes this is unavoidable because we do not yet have a test system that executes when the pull request is generated. Then, when we have that system, we will ask the people who make the pull request to correct those warnings before it is approved, or in case they don't know how to do it, we will try to help them. I think I use Ubuntu 21.10 (because it is the previous version to bring by default OpenSSL 3.x) and Debian 10 or 11 (I don't remember well, I think 11). And I haven't had any Warning reports during the compilation.

**Comment by Meltie2013** [comment]
I did run a workflow run for 20.04 displayed warnings during compiling while I was a work. Going to most likely make a PR for workflows for this project, so they are logged per commit. Also can fail on warnings if needed. I will see if I can get the complete warning list.

**Comment by pangolp** [comment]
Only 2 warnings were generated or were there more? @Tony931023

**Comment by Tony931023** [comment]
@pangolp yes

Quiero sacar un server de prueba para poder hacer reportes y que la comunidad tambien pueda hacer reportes

**Comment by pangolp** [comment]
> @pangolp yes
> 
> Quiero sacar un server de prueba para poder hacer reportes y que la comunidad tambien pueda hacer reportes

Tenemos un servidor de pruebas ya. Todos los datos están en el discord. Pero cuantos más reportes mejor. Sin embargo, no solo necesitamos reportes, también necesitamos desarrolladores.

**Comment by Meltie2013** [comment]
@pangolp @seobryn This is the commit those warnings are coming from.
```
Commit:        eb3e2312fb650ab59a270ea7a1b3137e005ae43c 
Author:        SargeroDeV <83485584+SargeroDeV@users.noreply.github.com> 
AuthorDate:    Mon Sep 12 15:11:37 2022 
Commit:        GitHub <noreply@github.com> 
CommitDate:    Mon Sep 12 15:11:37 2022 
```
@SargeroDeV 

Also the methods used are mismatched to begin with. Working on solution.

**Comment by Tony931023** [comment]
[ 11%] Building CXX object src/common/CMakeFiles/common.dir/Utilities/TaskScheduler.cpp.o
In file included from /home/cloud/firelands-cata/src/common/Utilities/TaskScheduler.cpp:18:
/home/cloud/firelands-cata/src/common/Utilities/TaskScheduler.h:430:11: warning: private field '_schedulerUnit' is not used [-Wunused-private-field]
    Unit* _schedulerUnit;
          ^
/home/cloud/firelands-cata/src/common/Utilities/TaskScheduler.h:431:17: warning: private field '_schedulerGob' is not used [-Wunused-private-field]
    GameObject* _schedulerGob;
                ^
2 warnings generated.

[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartScriptMgr.cpp.o
/home/cloud/firelands-cata/src/server/game/AI/SmartScripts/SmartScriptMgr.cpp:547:168: warning: format specifies type 'long' but the argument has type 'int32' (aka 'int') [-Wformat]
                LOG_ERROR("sql.sql", "SmartAIMgr: Entry " SI64FMTD " SourceType %u Event %u Action %u uses non-existent Creature entry %u as target_param1, skipped.", e.entryOrGuid, e.GetScriptType(), e.event_id, e.GetActionType(), e.target.invokerSummon.entry);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/cloud/firelands-cata/src/common/Logging/Log.h:186:53: note: expanded from macro 'LOG_ERROR'
    LOG_MESSAGE_BODY(filterType__, LOG_LEVEL_ERROR, __VA_ARGS__)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/cloud/firelands-cata/src/common/Logging/Log.h:157:32: note: expanded from macro 'LOG_MESSAGE_BODY'
                    check_args(__VA_ARGS__);                            \
                               ^~~~~~~~~~~
/home/cloud/firelands-cata/src/server/game/AI/SmartScripts/SmartScriptMgr.cpp:1696:161: warning: format specifies type 'long' but the argument has type 'int32' (aka 'int') [-Wformat]
                LOG_ERROR("sql.sql", "SmartScript: SMART_ACTION_SET_SPEED have wrong speed type %u for creature " SI64FMTD ", skipped", e.action.setSpeed.type, e.entryOrGuid);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
/home/cloud/firelands-cata/src/common/Logging/Log.h:186:53: note: expanded from macro 'LOG_ERROR'
    LOG_MESSAGE_BODY(filterType__, LOG_LEVEL_ERROR, __VA_ARGS__)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/cloud/firelands-cata/src/common/Logging/Log.h:157:32: note: expanded from macro 'LOG_MESSAGE_BODY'
                    check_args(__VA_ARGS__);                            \
                               ^~~~~~~~~~~
2 warnings generated.

**Comment by acidmanifesto** [comment]
https://github.com/FirelandsProject/firelands-cata/commit/3597ada541a3a5927a5d3b12b5971c85059705c3

At the moment only 3 warnings remain currently that i see.
But only warnings and not errirs.

**Comment by ZhxChen** [comment]
What dependencies are required for Ubuntu 22? I am encountering compilation errors.

make[2]: *** [src/common/CMakeFiles/common.dir/build.make:397: src/common/CMakeFiles/common.dir/Cryptography/OpenSSLCrypto.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:866: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by ZhxChen** [comment]
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp: In function ‘void lockingCallback(int, int, const char*, int)’:
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:28:16: error: ‘CRYPTO_LOCK’ was not declared in this scope
   28 |     if (mode & CRYPTO_LOCK)
      |                ^~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp: At global scope:
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:34:13: error: variable or field ‘threadIdCallback’ declared void
   34 | static void threadIdCallback(CRYPTO_THREADID* id)
      |             ^~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:34:30: error: ‘CRYPTO_THREADID’ was not declared in this scope
   34 | static void threadIdCallback(CRYPTO_THREADID* id)
      |                              ^~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:34:47: error: ‘id’ was not declared in this scope
   34 | static void threadIdCallback(CRYPTO_THREADID* id)
      |                                               ^~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp: In function ‘void OpenSSLCrypto::threadsSetup()’:
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:42:24: error: ‘CRYPTO_num_locks’ was not declared in this scope
   42 |     cryptoLocks.resize(CRYPTO_num_locks());
      |                        ^~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:48:12: error: ‘threadIdCallback’ was not declared in this scope
   48 |     (void)&threadIdCallback;
      |            ^~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:49:5: error: ‘CRYPTO_THREADID_set_callback’ was not declared in this scope
   49 |     CRYPTO_THREADID_set_callback(threadIdCallback);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:52:5: error: ‘CRYPTO_set_locking_callback’ was not declared in this scope
   52 |     CRYPTO_set_locking_callback(lockingCallback);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp: In function ‘void OpenSSLCrypto::threadsCleanup()’:
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:57:5: error: ‘CRYPTO_set_locking_callback’ was not declared in this scope
   57 |     CRYPTO_set_locking_callback(nullptr);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:58:5: error: ‘CRYPTO_THREADID_set_callback’ was not declared in this scope
   58 |     CRYPTO_THREADID_set_callback(nullptr);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zhxchen/Firelands/firelands-cata/src/common/Cryptography/OpenSSLCrypto.cpp:59:25: error: ‘CRYPTO_num_locks’ was not declared in this scope
   59 |     for(int i = 0 ; i < CRYPTO_num_locks(); ++i)
      |                         ^~~~~~~~~~~~~~~~
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:397: src/common/CMakeFiles/common.dir/Cryptography/OpenSSLCrypto.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:997: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by Meltie2013** [comment]
@ZhxChen What version of OpenSSL do you have?

**Comment by ZhxChen** [comment]
@Meltie2013 
zhxchen@wow434ser:~$ cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
zhxchen@wow434ser:~$ dpkg -s libboost-dev | grep Version
Version: 1.74.0.3ubuntu7
zhxchen@wow434ser:~$ dpkg -s libreadline-dev | grep Version
Version: 8.1.2-1
zhxchen@wow434ser:~$ mysql --version
mysql  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
zhxchen@wow434ser:~$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
zhxchen@wow434ser:~$ git --version
git version 2.34.1
zhxchen@wow434ser:~$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)



zhxchen@wow434ser:~/Firelands/firelands-cata/build$ sudo cmake "../" \
-DCMAKE_INSTALL_PREFIX=../firelands-release
-- Detected 64-bit platform - ok
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: SFMT enabled, SSE2 flags forced
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found MySQL executable: /usr/bin/mysql

* FirelandsCore revision   : 961099153b1e 2023-10-03 16:44:38 -0400 (master branch)
* FirelandsCore buildtype  : RelWithDebInfo

* Install core to        : /home/zhxchen/Firelands/firelands-cata/firelands-release
* Install libraries to   : /home/zhxchen/Firelands/firelands-cata/firelands-release/lib
* Install configs to              : /home/zhxchen/Firelands/firelands-cata/firelands-release/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (static)
* Build with modules     : Yes (static)
* Build map/vmap tools   : Yes (default)
* Build unit tests       : No (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Show source tree       : Yes (hierarchical)
* Use GIT revision hash  : Yes (default)

-- Running cmake hook: AFTER_LOAD_CONF
-- No hooks registered for AFTER_LOAD_CONF
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include

* Script configuration (static):
    |
    +- worldserver
    |   +- Commands
    |   +- Custom
    |   +- EasternKingdoms
    |   +- Events
    |   +- Kalimdor
    |   +- Maelstrom
    |   +- Northrend
    |   +- OutdoorPvP
    |   +- Outland
    |   +- Pet
    |   +- Spells
    |   +- World
    |

* Modules configuration (static):
  |

-- * Modules config list:
  |

-- Configuring done (2.4s)
-- Generating done (0.2s)
-- Build files have been written to: /home/zhxchen/Firelands/firelands-cata/build

**Comment by seobryn** [comment]
I'm Closing this issue because Iwas testing again And I dont receive this warnings.
